"""add diagnostic id to consultation

Revision ID: 32ff9121ca34
Revises: 70a6ec0afef5
Create Date: 2026-03-26 12:30:55.137227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ff9121ca34'
down_revision: Union[str, Sequence[str], None] = '70a6ec0afef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('diagnosis_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'diagnosis', ['diagnosis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'diagnosis_id')
    # ### end Alembic commands ###
