"""indexing user

Revision ID: 4971450ced3a
Revises: 8c80c9ab2573
Create Date: 2026-04-08 18:00:29.880735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4971450ced3a'
down_revision: Union[str, Sequence[str], None] = '8c80c9ab2573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_user_id_key'), 'auth', type_='unique')
    op.create_index(op.f('ix_auth_user_id'), 'auth', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth')
    op.create_unique_constraint(op.f('auth_user_id_key'), 'auth', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
